FROM eclipse-temurin:17-jdk-alpine
WORKDIR /app
COPY target/spring-boot-cicd-0.0.1-SNAPSHOT.jar spring-boot-cicd-0.0.1-SNAPSHOT.jar
EXPOSE 8080
CMD ["java","-jar","spring-boot-cicd-0.0.1-SNAPSHOT.jar"]
